services:
  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "3000:${TYPESENSE_PORT}"
    volumes:
      - ./typesense-data:/data
    command: "--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors"
